Feature comments
Solntmore/java-explore-with-me pull request #5
Opened 2023-02-14 17:25 UTC by Solntmore

add: Добавлен пакет Comments, основная модель Comment, DTO классы, сервис, маппер, репозиторий, кастомные исключения
add: В Event и EventFullDto добавлено поле comments
add: в классе UsersController добавлены энд-пойнты на создание, удаление и редактирование пользователя
add: Добавлен end-point admin/comment/{commentId} для модерации комментариев администратором.
fix: Метод deleteComment в CommentService переименован в userDeleteComment для уточнения функционала, в связи с появлением возможности удаления комментариев администратором
add: Добавлены postman тесты в папке postman для тестирования работы комментариев

2023-02-15 07:54 UTC, Fleaman777 requested changes

2023-02-15 07:54 UTC, Fleaman777 commented on ewm-serv/src/main/java/ru/practicum/ewmserv/comment/service/CommentService.java
>          if (!userRepository.existsById(userId)) {
похожая проверка есть в методе create, ее можно было бы вынести в общий метод

2023-02-15 07:54 UTC, Fleaman777 commented on ewm-serv/src/main/java/ru/practicum/ewmserv/comment/service/CommentService.java
>          if (!userRepository.existsById(userId)) {
и вместо этой проверки можно было бы искпользовать общий метод

2023-02-15 07:57 UTC, Fleaman777 commented
как-то конечно странно придумали,
с фича ветками и с мержом в main только, после сделанной фичи,
в таком случае получается, что фича имеет весь код, который писался в течение всего диплома, хотя по факту только несколько классов, при таком подходе тяжело проревьюить только фичу) да и с точки зрения разработки это неудобно,

как по мне, идеальней было бы
иметь dev ветку(что в принципе у тебя и есть), в которую бы мержились все ветки, а после последнего смерженной(когда весь диплом отревьюен), дев смержился бы в main

это не призыв к действию, просто мысли вслух)

2023-02-15 08:00 UTC, Solntmore commented
Согласен, я изначально и сделал ветку develop под эту логику, но потом сказали, что так делать не нужно и предложили такую схему. Собственно, не стал отклоняться от инструктажа, поэтому не стал мержить в develop, а сделал это в мейн.

2023-02-15 08:04 UTC, Solntmore commented on ewm-serv/src/main/java/ru/practicum/ewmserv/comment/service/CommentService.java
>          if (!userRepository.existsById(userId)) {
В методе create я не только проверяю на наличие, но и сразу достаю сущность Юзера, так как она необходима для дальнейшей работы. А в удалении и редактировании только проверяю наличие, не доставая его. Думаю, что создание логично оставить как есть, чтобы не делать два запросы в бд вместо одного, а вот сделать метод для просто проверки наличия юзера в случае создания и редактирования, согласен, было бы логично, так и сделаю.

2023-02-15 08:06 UTC, Solntmore commented
Чтобы было проще проверить, что именно добавлено:
3 энд-пойнта в классе UserController(create, update, userDeleteComment)
1 энд-пойнт в классе admin(adminDeleteComment). Администратор может тоже удалять комментарии, при чем не зависимо от даты публикации.

2023-02-16 06:36 UTC, Fleaman777 approved these changes

2023-02-28 18:21 UTC, merged